name: chrissx-Server-only-Plugin-Combo
author: chrissx
version: INTERNAL
main: de.chrissx.server.mainplugin.Main

commands:
 hp:
 ping:
 ragemode:
 rmlist:
 rmsetup:
 rmstats:
 rmstart:
 savelog:
 agl:
 walls:
 pos1:
 pos2:
 set:
 biome:
 undo:
 commandspy:
 i:
 item:
 give:
 v:
 vanish:
 nick:
 nickname:
 ip:
 address:
 pl:
 plugin:
 sethome:
 home:
 color:
 broadcast:
 bc:
 skin:
 regen:
 create:
 teleport:
 worldlist:
 delete:
 help:
 pl:
 plugins:
 stats:
 speed: