package de.chrissx.server.shared;

public enum CommandError {
NO_OP, NO_PLAYER, NOT_ENOUGH_ARGUMENTS, TOO_MANY_ARGUMENTS, WRONG_USAGE, PLAYER_NOT_FOUND, INTERNAL, ENUM_ERROR, NOT_ADDED_TO_SWITCH_CASE
}
